"""add error column to execution_steps

Revision ID: 18234630b78b
Revises: 20481645c649
Create Date: 2026-08-08 21:01:58.701718
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '18234630b78b'
down_revision: str | None = '20481645c649'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_steps', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_steps', 'error')
    # ### end Alembic commands ###
