"""seed agents

Seeds the `agents` table with the 4 required agent types. Data, not schema —
this can't be autogenerated from the models, so unlike the schema migration
before it, this one is hand-written. GET /agents and plan validation both
depend on these rows existing.

Revision ID: 7c3a6ca43ab6
Revises: 06d8800ee135
Create Date: 2026-08-07 15:28:19.054616
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7c3a6ca43ab6'
down_revision: str | None = '06d8800ee135'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


AGENTS_TABLE = sa.table(
    "agents",
    sa.column("name", sa.String),
    sa.column("capabilities", sa.JSON),
    sa.column("configuration", sa.JSON),
)

AGENTS = [
    {"name": "research", "capabilities": ["search", "summarize", "cite_sources"], "configuration": {}},
    {
        "name": "writing",
        "capabilities": ["generate_content", "edit", "format_output"],
        "configuration": {},
    },
    {
        "name": "analysis",
        "capabilities": ["analyze_data", "compare_options", "identify_patterns"],
        "configuration": {},
    },
    {"name": "code", "capabilities": ["generate_code", "explain_code", "debug"], "configuration": {}},
]


def upgrade() -> None:
    op.bulk_insert(AGENTS_TABLE, AGENTS)


def downgrade() -> None:
    op.execute(AGENTS_TABLE.delete())
